### ISSUE TITLE
Not a bug,  C++20 removal of std::result_of

### ISSUE THREAD

**Issue by dmiller423** [bisqwit/TinyDeflate#2]
As title suggests building for C++20 where std::result_of has been removed after being deprecated in C++17,  fails. I've implemented a generic solution, and what's actually being used simply copied from headers ,  thus not using a pull request.   If you would consider adding proper support that would be ideal.

Putting this snipped at the top of the gunzip.hh then simply removing std::  from instances of result_of_t. 

```C
#if __cplusplus > 202000UL

// Normal solution for result_of , not what's being used
template <typename F, typename... Args>
struct result_of<F(Args...)> : std::invoke_result<F, Args...> {};

template <class _Fty>
struct result_of { // explain usage
    static_assert(_Always_false<_Fty>, "result_of<CallableType> is invalid; use "
        "result_of<CallableType(zero or more argument types)> instead.");
};

template <class _Ty>
using result_of_t = typename result_of<_Ty>::type;

#endif
```

**Comment by bisqwit** [comment]
Thank you for the heads-up!
