### ISSUE TITLE
Response to certain lies

### ISSUE THREAD

**Issue by ghost** [bisqwit/TinyDeflate#5]
This is a response to some false claims made which use the respected word "Engineering" in it.
Hey
@bisqwit  just wanted to say that Engineering has nothing to do with sitting behind a keyboard and writing code. There is no such thing as "reverse" "engineering". Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. Software devs are claiming the most ridiculous of false claims these days. 

Software dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering.

Mechanical Engineering is the only Engineering.

bye bye

**Comment by bisqwit** [comment]
Spammer.

**Comment by paulwratt** [comment]
hmm..  65k followers

**Comment by bisqwit** [comment]
6.5k, not 65k. The original poster’s account was deleted, most probably due to violation of terms of use (spamming). In these situations, Github replaces the account in the posts with Ghost, a system account that replaces all deleted accounts.
